// Generated by scripts/build-server-plugin.mjs from the server manifest.
export const SERVER_PLUGIN_ID = "littlewhitebox-server";
export const SERVER_PLUGIN_NAME = "LittleWhiteBox Server";
export const SERVER_PLUGIN_VERSION = "3.0.0";
export const SERVER_PLUGIN_BASE = `/api/plugins/${SERVER_PLUGIN_ID}`;
