import { defineLandscapeScene } from '../world/landscape.js';
import { feature } from './landscape-content.js';

export const COURTYARD_CAMP = defineLandscapeScene({
    id: 'camp', safe: true,
    anchors: {
        start: { x: -22, y: 16 }, road: { x: 0, y: -53 }, clinic: { x: -13, y: 12 }, guard: { x: 7, y: -39 },
        kouzi: { x: 32, y: 8 }, anian: { x: -18, y: 15 }, rest: { x: -3, y: 15 }, cargo: { x: 16, y: 7 },
        postern: { x: -42, y: 7 }, receiving: { x: -16, y: 16 },
        gatehouse: { x: 11, y: -37 }, clinic_back: { x: -29, y: 8 }, registry: { x: -10, y: 15 },
    },
    exits: [
        { id: 'road', anchor: 'road', to: 'crossroads', arrival: 'camp' },
        { id: 'postern', anchor: 'postern', to: 'cells', arrival: 'postern', condition: { all: ['postern_opened'] } },
    ],
    objects: [
        { id: 'rest', anchor: 'rest', kind: 'rest' },
        { id: 'cargo', anchor: 'cargo', kind: 'inspect', passage: 'cargo', condition: { all: ['warden_defeated'] } },
    ],
    landscape: {
        vista: 'camp', surface: 'street', bounds: { x: 0, z: -8, width: 96, depth: 100 },
        suspended: [
            { kind: 'pipe', from: [-35.7, 5.3, 36], to: [-35.7, 5.3, -46] },
            { kind: 'pipe', from: [-36, 4.8, 4], to: [-19, 4.8, 4] },
            { kind: 'pipe', from: [-27, 5.2, 28], to: [-27, 5.2, 4] },
            { kind: 'pipe', from: [-8, 5.4, -12], to: [12, 5.4, -12] },
            { kind: 'pipe', from: [12, 5.4, -12], to: [12, 5.4, -48] },
            { kind: 'pipe', from: [12, 5.4, -12], to: [34, 5.4, -12] },
            { kind: 'pipe', from: [34, 5.4, -12], to: [34, 5.4, 20] },
            { kind: 'washing', from: [-27, 3.5, 25], to: [-12, 3.8, 20] },
            { kind: 'washing', from: [15, 3.7, 20], to: [28, 4.2, 28] },
        ],
        gates: [{ id: 'postern', footprint: { x: -36, z: 7, width: 2, depth: 4 }, condition: { all: ['postern_opened'] } }],
        roads: [
            { points: [[0, 36], [0, 16], [-4, 10], [-4, 1], [2, -12], [0, -24], [0, -53]], width: 4 },
            { points: [[-33, 18], [-23, 15], [-14, 13], [0, 11], [16, 8], [28, 8]], width: 3 },
            { points: [[-31, 32], [-30, 19], [-29, 8]], width: 3 },
            { points: [[-27, 18], [-22, 18], [-17, 23.2], [-12, 23.2]], width: 2 },
            { points: [[0, -36], [17, -37], [27, -43]], width: 4 },
        ],
        features: [
            feature('clinic', 'clinic', -19, 4, 14, 10),
            feature('storehouse', 'storehouse', 12, -9, 12, 12),
            feature('hearth', 'stove', 0, 6, 4, 4),
            feature('rest-bench', 'bench', -5, 15, 2, 4),
            feature('wagon', 'wagon', 22, 3, 4, 6),
            feature('supply-crates', 'supplies', 20, -5, 4, 4),
            feature('drying-shed', 'workshop', -29, 0, 4, 10, { height: 3.5 }),
            feature('herbs-small', 'medicine', -23, 10, 6, 2),
            feature('menders-home', 'dwelling', -12, 20, 4, 4, { height: 3.3, tint: 'rose' }),
            feature('eastern-home', 'dwelling', 15, 20, 4, 4, { height: 4.1 }),
            feature('wall-home', 'dwelling', -31, -12, 4, 4, { height: 5 }),
            feature('charcoal-home', 'dwelling', 34, -16, 4, 4, { height: 4.7 }),
            feature('pipe-home', 'dwelling', -16, -19, 4, 4, { height: 3.8 }),
            feature('canal-west', 'water', -26, -28, 44, 4),
            feature('canal-east', 'water', 26, -28, 44, 4),
            feature('bridge-west', 'wall', -5, -28, 2, 6, { height: .8 }),
            feature('bridge-east', 'wall', 5, -28, 2, 6, { height: .8 }),
            feature('gate-west', 'wall', -26, -49, 44, 4, { height: 6 }),
            feature('gate-east', 'wall', 26, -49, 44, 4, { height: 6 }),
            feature('west-watchtower', 'tower', -8, -49, 6, 8, { height: 12 }),
            feature('east-watchtower', 'tower', 8, -49, 6, 8, { height: 12 }),
            feature('departure-arch', 'arch', 0, -49, 10, 4, { height: 8 }),
            feature('west-boundary', 'wall', -37, -26, 2, 62, { height: 7, wallUse: 'homes' }),
            feature('postern-bottom', 'wall', -37, 25, 2, 32, { height: 7, wallUse: 'homes' }),
            feature('south-boundary', 'wall', 0, 40, 96, 4, { height: 1 }),
            feature('east-boundary', 'wall', 46, -8, 4, 96, { height: 1.2 }),
            feature('postern-end', 'wall', -47, -8, 2, 100, { height: 2.4 }),
            feature('north-boundary', 'wall', 0, -57, 96, 2, { height: 5 }),
            feature('roadside-workshop', 'workshop', -17, -38, 16, 8, { height: 4 }),
            feature('lookout-ruin', 'ruin', 24, -38, 6, 6, { height: 3 }),
            feature('arrival-home', 'dwelling', -27, 28, 6, 6, { height: 4.3 }),
            feature('eastern-workshop', 'workshop', 28, 30, 6, 6, { height: 3.7 }),
            feature('wall-row', 'dwelling', -24, -21, 18, 4, { height: 4.5 }),
            feature('roadside-homes', 'dwelling', -8, -12, 4, 10, { height: 4.2 }),
            feature('clinic-back-shed', 'workshop', -20, -5, 16, 2, { height: 2.6 }),
        ],
    },
});

export const COURTYARD_CROSSROADS = defineLandscapeScene({
    id: 'crossroads', safe: false,
    anchors: {
        camp: { x: 0, y: 43 }, gate: { x: 0, y: -43 }, waterway: { x: 34, y: 7 }, roots: { x: -36, y: -13 },
        warning: { x: 5, y: 19 }, encounter: { x: 0, y: 9 }, patrol: { x: -4, y: -8 }, lookout: { x: 8, y: -18 },
    },
    exits: [
        { id: 'camp', anchor: 'camp', to: 'camp', arrival: 'road' },
        { id: 'gate', anchor: 'gate', to: 'gate', arrival: 'crossroads', condition: { all: ['crossroads_cleared'] } },
        { id: 'waterway', anchor: 'waterway', to: 'waterway', arrival: 'crossroads', condition: { all: ['crossroads_cleared'] } },
        { id: 'roots', anchor: 'roots', to: 'roots', arrival: 'crossroads', condition: { all: ['warden_defeated'] } },
    ], objects: [{ id: 'warning', anchor: 'warning', kind: 'inspect', passage: 'warning' }],
    landscape: {
        vista: 'ramparts', surface: 'grass', bounds: { x: 0, z: 0, width: 96, depth: 96 },
        gates: [{ id: 'roots', footprint: { x: -29, z: -13, width: 2, depth: 6 }, condition: { all: ['warden_defeated'] } }],
        roads: [
            { points: [[0, 44], [0, 28], [-4, 14], [2, 0], [0, -20], [0, -44]], width: 8 },
            { points: [[-4, 14], [14, 14], [24, 7], [35, 7]], width: 4 },
            { points: [[0, -13], [-18, -13], [-37, -13]], width: 5 },
        ],
        features: [
            feature('wall-west', 'wall', -30, -32, 2, 32, { height: 3 }),
            feature('wall-west-low', 'wall', -30, 19, 2, 58, { height: 2 }),
            feature('wall-east', 'wall', 24, -25, 4, 44, { height: 7 }),
            feature('rampart-tower', 'tower', 24, -16, 8, 8, { height: 15 }),
            feature('gate-tower-left', 'tower', -8, -41, 6, 8, { height: 11 }),
            feature('gate-tower-right', 'tower', 8, -41, 6, 8, { height: 11 }),
            feature('north-arch', 'arch', 0, -41, 10, 4, { height: 8 }),
            feature('west-gate-wall', 'wall', -26, -43, 40, 4, { height: 5 }),
            feature('east-gate-wall', 'wall', 36, -43, 20, 4, { height: 5 }),
            feature('road-ruin', 'ruin', -12, 1, 6, 6, { height: 3.5 }),
            feature('fallen-column', 'ruin', 12, -2, 4, 4, { height: 1.2 }),
            feature('road-tree', 'tree', -17, 27, 4, 4, { height: 9, tint: 'amber' }),
            feature('roots-tree', 'tree', -39, -25, 6, 6, { height: 13, tint: 'sage' }),
            feature('southern-tree', 'tree', 17, 37, 4, 4, { height: 9, tint: 'sage' }),
            feature('arrival-watch-west', 'tower', -8, 44, 6, 8, { height: 10 }),
            feature('arrival-watch-east', 'tower', 8, 44, 6, 8, { height: 10 }),
            feature('arrival-arch', 'arch', 0, 44, 10, 4, { height: 8 }),
            feature('broken-convoy', 'wagon', -12, 19, 4, 6, { damaged: true }),
            feature('convoy-supplies', 'supplies', -16, 16, 4, 4),
            feature('stranded-cargo', 'cargo', -24, 28, 8, 12),
            feature('stranded-fuel', 'fuel', 18, 25, 6, 8),
            feature('old-border', 'thicket', -18, -6, 14, 4),
            feature('waterway-bank', 'water', 37, 21, 22, 16),
            feature('north-boundary', 'wall', 0, -47, 96, 2, { height: 5 }),
            feature('south-boundary-west', 'wall', -26, 47, 44, 2, { height: 5 }),
            feature('south-boundary-east', 'wall', 26, 47, 44, 2, { height: 5 }),
            feature('west-boundary', 'wall', -47, 0, 2, 96, { height: 2 }),
            feature('east-boundary', 'wall', 47, 0, 2, 96, { height: 2 }),
        ],
    },
});
