import { MEMORY_DATA_COPY } from '../data/memory-copy.js';

export const MEMORY_COPY = Object.freeze({
    tab: 'Agent', toggle: '允许 Agent 维护记忆', scope: '所有聊天',
    behavior: '保存开关不会调用模型；下一批总结保存后开始检查大总结和逐楼锚点。',
    api: '使用共享 Agent API，可在Agent模块任意功能中设置，如小白 OS 的「Agent API」；已配置则无需重复设置。',
    heading: '当前聊天的维护成果', review: '复审一次', cancel: '取消运行', repair: '补齐索引', more: '更早记录',
    empty: '还没有维护成果', loading: '正在读取维护成果…',
    settingsSaved: '设置已保存', settingsFailed: '设置未能保存',
    before: '修改前', after: '修改后', reason: '理由', evidence: '依据', absent: '已移除',
    retired: { source_changed: '原文已变更：此锚点操作已失效，不再参与撤销或索引补齐。',
        anchors_cleared: '锚点已清空：此操作已失效，不再参与撤销或索引补齐。' },
    summary: '大总结', anchors: '锚点', merges: '事件合并', reviewed: '已检查', unreviewed: '未检查',
    unresolved: '无法查证', missing: '缺失锚点', noChanges: '本次没有修改',
    boundary: floor => `总结至第 ${floor} 楼`, floor: floor => `第 ${floor} 楼`,
    count: (label, count) => `${label} ${count}`,
    collections: { events: '事件', facts: '持续事实', characters: '人物', arcs: '弧光', keywords: '关键词', characterAliases: '别名', anchors: '逐楼锚点' },
    anchorStates: { missing: '未生成', fail: '提取失败' },
    states: { idle: '', queued: '等待前一轮结束', running: '正在复审', saving: '正在确认保存', indexing: '修改已保存，正在补齐索引',
        saved: '维护已保存', cancelled: '已取消未提交的复审', failed: '本次复审未保存', unconfirmed: MEMORY_DATA_COPY.unconfirmed,
        source_invalid: MEMORY_DATA_COPY.sourceInvalid, history_invalid: MEMORY_DATA_COPY.historyInvalid },
    indexPending: '修改已保存，部分索引待补齐。补齐索引不会重新进行语义复审。',
    errors: { not_configured: '共享 Agent 主预设尚未配置模型或地址。', no_boundary: '当前聊天还没有可复审的有效总结。',
        agent_auth: '共享 Agent API 的凭据不可用，请在 Agent API 设置中更新。',
        agent_balance: '共享 Agent API 余额不足。', agent_rate: '共享 Agent API 暂时限流。',
        agent_model: '共享 Agent API 当前不提供所选模型。',
        conflict: '原文或记忆已经变化，旧草稿未覆盖新内容。', budget: '已达到本次复审上限，未完成草稿没有保存。',
        agent_failed: 'Agent 请求未完成，草稿没有保存。', incomplete_finish: 'Agent 未完成复审，草稿没有保存。',
        metadata_not_saved: '服务器未保存修改，已恢复修改前的记忆。', metadata_save_conflict: '服务器内容已变化，保存结果需核对。',
        metadata_save_unconfirmed: '暂时无法回查服务器，不能确认保存。', metadata_target_unavailable: '无法定位当前聊天文件。',
        index_failed: '索引补齐失败。', index_read_failed: '索引状态读取失败。', load_failed: '维护成果读取失败。' },
});
